# Generated by Django 2.2.13 on 2021-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_feed', '0001_squashed_0005_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikifeedpublishcommunity',
            name='current_growth',
        ),
        migrations.RemoveField(
            model_name='wikifeedpublishcommunity',
            name='kernel_type',
        ),
        migrations.DeleteModel(
            name='WikiFeedCommunity',
        ),
        migrations.DeleteModel(
            name='WikiFeedPublishCommunity',
        ),
    ]
