# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20171119_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestation',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
