# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('core', '0021_manifestation_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataScopeUser',
        )
    ]
