# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20190131_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collective',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='growth',
            options={'get_latest_by': 'id', 'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='individual',
            options={'get_latest_by': 'id', 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='manifestation',
            options={'get_latest_by': 'id', 'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='collective',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collective',
            name='referee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
