# Generated by Django 3.2 on 2021-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_squashed_0029_alter_data_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleimage',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='googleimage',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googletext',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='googletext',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googletranslate',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='googletranslate',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagedownload',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imagedownload',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kledinglisting',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kledinglisting',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikidataitems',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikidataitems',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediacategories',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediacategories',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediacategorymembers',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediacategorymembers',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaedit',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediaedit',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialistpages',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipedialistpages',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialogin',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipedialogin',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediapageviewdetails',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediapageviewdetails',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediarecentchanges',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediarecentchanges',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediarevisions',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediarevisions',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediasearch',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediasearch',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatoken',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediatoken',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatransclusions',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediatransclusions',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatranslate',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wikipediatranslate',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
