# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0022_googletext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipediacategories',
            options={},
        ),
    ]
