# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0023_auto_20171003_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipediacategories',
            options={'verbose_name': 'Wikipedia category', 'verbose_name_plural': 'Wikipedia categories'},
        ),
        migrations.AlterField(
            model_name='acteursspotprofile',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='acteursspotprofile',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='acteursspotprofile',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='benfcastingprofile',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='benfcastingprofile',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='benfcastingprofile',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googleimage',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googleimage',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='googleimage',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googletext',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googletext',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='googletext',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='googletranslate',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='googletranslate',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='googletranslate',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagedownload',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagedownload',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='imagedownload',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kledinglisting',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='kledinglisting',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='kledinglisting',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moederannecastingsearch',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='moederannecastingsearch',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='moederannecastingsearch',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moederannecastingsession',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='moederannecastingsession',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='moederannecastingsession',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officialannouncementsdocumentnetherlands',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='officialannouncementsdocumentnetherlands',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='officialannouncementsdocumentnetherlands',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='officialannouncementsnetherlands',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='officialannouncementsnetherlands',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='officialannouncementsnetherlands',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikidataitems',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikidataitems',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikidataitems',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediacategories',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediacategories',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediacategories',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediacategorymembers',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediacategorymembers',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediacategorymembers',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediaedit',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaedit',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediaedit',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipedialistpages',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialistpages',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipedialistpages',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipedialogin',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialogin',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipedialogin',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediapageviewdetails',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediapageviewdetails',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediapageviewdetails',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediarecentchanges',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediarecentchanges',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediarecentchanges',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediarevisions',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediarevisions',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediarevisions',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediasearch',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediasearch',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediasearch',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediatoken',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatoken',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediatoken',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediatransclusions',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatransclusions',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediatransclusions',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wikipediatranslate',
            name='body',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediatranslate',
            name='head',
            field=json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='wikipediatranslate',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
