# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0024_auto_20171119_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteursspotprofile',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='benfcastingprofile',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='moederannecastingsearch',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='moederannecastingsession',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='ActeursSpotProfile',
        ),
        migrations.DeleteModel(
            name='BenfCastingProfile',
        ),
        migrations.DeleteModel(
            name='MoederAnneCastingSearch',
        ),
        migrations.DeleteModel(
            name='MoederAnneCastingSession',
        ),
    ]
