# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0025_auto_20180818_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialannouncementsdocumentnetherlands',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='officialannouncementsnetherlands',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='OfficialAnnouncementsDocumentNetherlands',
        ),
        migrations.DeleteModel(
            name='OfficialAnnouncementsNetherlands',
        ),
    ]
