# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 16:08
from __future__ import unicode_literals

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('online_discourse', '0005_webtextresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoursesearchcommunity',
            name='aggregates',
            field=json_field.fields.JSONField(default={}, help_text='Enter a valid JSON object'),
        ),
    ]
