from online_discourse.discourse import DiscourseConfiguration


SINGULAR_SUBJECTS = [
    # Actualiteiten
    "oorlog slachtoffer",
    "oorlog getraumatiseerde",
    "Syrische vluchteling",
    "Asiel Zoekers Centrum",
    "AZC",
    "asielzoekers opvang",
    "smokkelaar",
    "opvang land",
    "opvang in de regio",
    # Allochtoon
    "allochtoon",
    "zwarte Nederlander",
    "gekleurde Nederlander",
    "bruine Nederlander",
    "vluchteling",
    "ontheemde",
    "statushouder",
    "illegale",
    "eerste generatie",
    "tweede generatie",
    "derde generatie",
    "1e generatie",
    "2e generatie",
    "3e generatie",
    "immigrant",
    "nieuwe Nederlander",
    "allochtoon",
    "gelukzoeker",
    "Moslim",
    "Islamiet",
    "Molukker",
    "Turk",
    "Marokkaan",
    "Surinamer",
    "Indonesier",
    "Antiliaan",
    "Caribisch",
    "arbeidsmigrant",
    "werkzoeker",
    "flexmigrant",
    "buitenlander",
    # Autochtoon
    "Nederlander",
    "Nederlands",
    "Hollander",
    "Hollands",
    "autochtone Nederlander",
    "echte Nederlander",
    "echte Hollander",
    "allochtone Nederlander",
    "witte Nederlander",
    "blanke Nederlander",
    "blanke Hollander",
    "autochtoon",
    "kolonist",
    # Slang
    "Mocro",
    "Suri",
    "Kaaskop",
    "Indo",
    # Institutioneel
    "werkvergunning",
    "expat",
    "integratie",
    "inburgeren",
    "inburgering",
    "assimilatie",
]

PLURAL_SUBJECTS = [
    # Actualiteiten
    "oorlog slachtoffers",
    "oorlog getraumatiseerden",
    "Syrische vluchtelingen",
    "Asiel Zoekers Centra",
    "smokkelaars",
    "opvang landen",
    # Allochtoon
    "allochtonen",
    "zwarte Nederlanders",
    "gekleurde Nederlanders",
    "bruine Nederlanders",
    "vluchtelingen",
    "ontheemden",
    "statushouders",
    "illegalen",
    "immigranten",
    "nieuwe Nederlanders",
    "allochtonen",
    "gelukzoekers",
    "Moslims",
    "Islamieten",
    "Molukkers",
    "Turken",
    "Marokkanen",
    "Surinamers",
    "Indonesiers",
    "Antilianen",
    "arbeidsmigranten",
    "werkzoekers",
    "flexmigranten",
    "buitenlanders",
    # Autochtoon
    "Nederlanders",
    "Hollanders",
    "autochtone Nederlanders",
    "echte Nederlanders",
    "echte Hollanders",
    "allochtone Nederlanders",
    "witte Nederlanders",
    "blanke Nederlanders",
    "blanke Hollanders",
    "autochtonen",
    "kolonisten",
    # Slang
    "Mocros",
    "Suris",
    "Kaaskoppen",
    "Indos",
    # Institutioneel
    "werkvergunningen",
    "expats",
]

DESCRIPTIVE_ADJECTIVES = [
    "bedreiging",
    "gevaar",
    "risico",
    "intimiderend"
    "verrijking",
    "aanwinst",
    "versterking"
    "plicht",
    "taak",
    "opdracht",
    "verantwoordelijkheid",
    "last",
    "kwelling",
    "ongerief",
    "ongemak",
    "verplichting",
    "voorschrift",
    "noodzaak",
    "belasting",
    "hinder",
    "kansloos",
    "hopeloos",
    "uitzichtloos",
    "zonder mogelijkheden",
    "kansrijk",
    "veelbelovend",
    "kansarm",
    "perspectiefloos",
    "weinig mogelijkheden",
    "mislukt"
    "geflopt",
    "gefaald",
    "mislukte",
    "mislukkeling",
    "terrorist",
    "geweldpleger",
    "misdadiger",
    "verkrachter",
    "moordenaar",
    "fraudeur",
    "terroristische"
    "onschuldig",
    "ongevaarlijk",
    "lief",
    "geen vlieg kwaad",
    "gevaarlijk",
    "riskant",
    "een kans",
    "mogelijkheid",
    "gelegenheid",
    "toevoeging",
    "aanvulling",
    "crimineel",
    "delinquent",
    "veroordeeld",
    "schuldig",
    "oververtegenwoordigd",
    "bovengemiddeld",
    "huisvesting",
    "onderdak",
    "inwoning",
    "verblijf",
    "onderkomen",
    "wonen",
    "vestigen",
    "vertoeven",
    "huisvesten",
    "verblijven",
    "smokkelen",
    "bedriegen",
    "frauderen",
    "mensenhandel",
    "mensensmokkel",
    "economisch",
    "economische",
    "werk",
    "arbeid",
    "bezigheid",
    "betrekking",
    "functie",
    "inkomen",
    "loon"
    "werk en inkomen",
    "uitkering",
    "bijslag",
    "compensatie",
    "werkloos",
    "zonder werk",
    "ondernemen",
    "opzetten",
    "eigen bedrijf",
    "onderneming",
    "eenmanszaak",
    "zielig",
    "treurig",
    # Continue here!
    "uitbuiten",
    "uitbuiters",
    "uitkering trekkers",
    "fraudeurs",
    "ondankbaar",
    "bureaucratisch",
    "bureaucratische",
    "onterecht",
    "uitbuiting",
    "uitbuiters",
    "Turkse",
    "Marokkaanse",
    "Surinaamse",
    "Indische",
    "Antiliaanse",
    "zielepoten",
    "bevoorrecht",
    "privilege",
    "terugkeren",
    "blijven",
    "illegaliteit",
    "dakloos",
    "normen en waarden",
    "andere cultuur",
    "gediscrimineerd",
    "racisten",
    "racistisch",
    "superieur",
    "supremacy",
    "ras",
    "sociaal-economisch",
    "achtergrond",
    "afkomst"
]

immigranten = DiscourseConfiguration(
    language="nl",
    singular_subjects=SINGULAR_SUBJECTS,
    plural_subjects=PLURAL_SUBJECTS,
    descriptive_adjectives=DESCRIPTIVE_ADJECTIVES
)
