# Generated by Django 3.2 on 2021-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_data', '0001_squashed_0007_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialannouncementsdocumentnetherlands',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='officialannouncementsdocumentnetherlands',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='officialannouncementsnetherlands',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='officialannouncementsnetherlands',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
