# Generated by Django 3.2.19 on 2024-04-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_data', '0002_datagrowth_v017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialannouncementsdocumentnetherlands',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='officialannouncementsnetherlands',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='DutchParliamentarySeatingTranscriptsCommunity',
        ),
        migrations.DeleteModel(
            name='OfficialAnnouncementsDocumentNetherlands',
        ),
        migrations.DeleteModel(
            name='OfficialAnnouncementsNetherlands',
        ),
    ]
