# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0002_empty_schema_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandrecognitionservice',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clothingimagedownload',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clothingtyperecognitionservice',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
