# Generated by Django 3.2 on 2021-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0004_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='document',
            name='schema',
        ),
        migrations.AlterField(
            model_name='brandrecognitionservice',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='brandrecognitionservice',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clothingimagedownload',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clothingimagedownload',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clothingtyperecognitionservice',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='clothingtyperecognitionservice',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='imagefeatures',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
