# Generated by Django 3.2 on 2021-05-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0005_datagrowth_v017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFeatures',
        ),
    ]
