# Generated by Django 2.2 on 2019-12-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified at')),
                ('route', models.CharField(db_index=True, max_length=256, verbose_name='route')),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch')], db_index=True, max_length=5, verbose_name='locale')),
                ('type', models.CharField(choices=[('Page', 'Page'), ('Webpack', 'Webpack')], max_length=20, verbose_name='type')),
                ('package', models.CharField(max_length=50, verbose_name='package')),
                ('version', models.CharField(blank=True, max_length=8, null=True, verbose_name='version')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(max_length=255, verbose_name='description')),
                ('static_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='static image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.Site', verbose_name='website')),
            ],
            options={
                'unique_together': {('route', 'language')},
            },
        ),
    ]
