# Generated by Django 2.2 on 2020-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapp',
            name='tracker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tracker'),
        ),
    ]
