# Generated by Django 2.2.13 on 2020-12-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('apps', '0002_tracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webapp',
            unique_together={('route', 'language', 'site')},
        ),
    ]
