# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0004_imagefeatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryCommunity',
            new_name='ClothingInventoryCommunity',
        ),
        migrations.AlterModelOptions(
            name='clothinginventorycommunity',
            options={'verbose_name': 'Clothing inventory community', 'verbose_name_plural': 'Clothing inventory communities'},
        ),
    ]
