# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20180818_1827'),
        ('future_fashion', '0006_auto_20180912_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorClothingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('processing_permission', models.BooleanField(default=False)),
                ('top_color', models.CharField(max_length=6)),
                ('bottom_color', models.CharField(max_length=6)),
                ('match_style', models.CharField(blank=True, max_length=20, null=True)),
                ('bottom_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Individual')),
                ('top_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Individual')),
            ],
        ),
    ]
