# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0007_colorclothingset'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorclothingset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
