# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-23 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('future_fashion', '0011_collection_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorclothingset',
            name='bottom_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='future_fashion.Document'),
        ),
        migrations.AlterField(
            model_name='colorclothingset',
            name='top_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='future_fashion.Document'),
        ),
    ]
