from online_discourse.discourse import DiscourseConfiguration


SINGULAR_SUBJECTS = [
    "parent",
    "caretaker",
    "family",
    "family model",
    "mother",
    "father",
    "couple",
    "single",
    "adoption",
    "child",
    "kid",
    "baby",
    "partner",
    "community",
    "population",
    "generation",
]

PLURAL_SUBJECTS = [
    "families",
    "family models",
    "babies",
    "societies",
    "communities",
]

DESCRIPTIVE_ADJECTIVES = [
    "parenthood",
    "responsibility",
    "sexuality",
    "sexes",
    "gender",
    "equality",
    "role",
    "expectation",
    "choice",
    "decision",
    "worries",
    "concern",
    "life",
    "lives",
    "happiness",
    "career",
    "job",
    "work",
    "purpose",
    "reason",
    "fulfilment",
    "influence",
    "conception",
    "procreation",
    "reproduction",
    "nature",
    "culture",
    "biology",
    "society",
    "social",
    "technology",
    "medicine",
    "body",
    "mind",
    "love",
    "romance",
    "relationship",
    "motivation",
    "commitment",
    "emotion",
    "control",
    "psyche",
    "individualism",
    "collectivism",
    "alternative",
    "norm",
    "earth",
    "planet",
    "future",
    "age",
    "time",
    "plan",
    "capitalism",
    "philosophy",
    "economy",
    "ideology"
]

family_planning = DiscourseConfiguration(
    title="Family Planning",
    description="Many people at some point face the question whether they want to start a family. " + \
                "Most people choose a traditional family, but there are alternatives to choose from.",
    language="en",
    singular_subjects=SINGULAR_SUBJECTS,
    plural_subjects=PLURAL_SUBJECTS,
    descriptive_adjectives=DESCRIPTIVE_ADJECTIVES
)
