# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trolls', '0002_auto_20171119_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditlist',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='redditpermalink',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='redditscrapecommunity',
            name='current_growth',
        ),
        migrations.RemoveField(
            model_name='redditscrapecommunity',
            name='kernel_type',
        ),
        migrations.DeleteModel(
            name='RedditList',
        ),
        migrations.DeleteModel(
            name='RedditPermalink',
        ),
        migrations.DeleteModel(
            name='RedditScrapeCommunity',
        ),
    ]
