# Generated by Django 2.2.13 on 2021-04-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_utrecht', '0008_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditlist',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='redditpermalink',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='redditscrapecommunity',
            name='current_growth',
        ),
        migrations.RemoveField(
            model_name='redditscrapecommunity',
            name='kernel_type',
        ),
        migrations.RemoveField(
            model_name='uniformimagedownload',
            name='retainer_type',
        ),
        migrations.RemoveField(
            model_name='uniformimagescommunity',
            name='current_growth',
        ),
        migrations.RemoveField(
            model_name='uniformimagescommunity',
            name='kernel_type',
        ),
        migrations.DeleteModel(
            name='RedditImageDownload',
        ),
        migrations.DeleteModel(
            name='RedditList',
        ),
        migrations.DeleteModel(
            name='RedditPermalink',
        ),
        migrations.DeleteModel(
            name='RedditScrapeCommunity',
        ),
        migrations.DeleteModel(
            name='UniformImageDownload',
        ),
        migrations.DeleteModel(
            name='UniformImagesCommunity',
        ),
    ]
