from online_discourse.discourse import DiscourseConfiguration


SINGULAR_SUBJECTS = [
    # Actualiteiten
    "oorlog slachtoffer",
    "oorlog getraumatiseerde",
    "Syrische vluchteling",
    "Oekrainse vluchteling",
    "Asiel Zoekers Centrum",
    "AZC",
    "asielzoekers opvang",
    "smokkelaar",
    "opvang land",
    "opvang in de regio",
    "klimaatvluchteling"
    # Allochtoon
    "allochtoon",
    "zwarte Nederlander",
    "gekleurde Nederlander",
    "bruine Nederlander",
    "vluchteling",
    "ontheemde",
    "statushouder",
    "illegale",
    "eerste generatie",
    "tweede generatie",
    "derde generatie",
    "1e generatie",
    "2e generatie",
    "3e generatie",
    "immigrant",
    "nieuwe Nederlander",
    "gelukzoeker",
    "Moslim",
    "Islamiet",
    "Molukker",
    "Turk",
    "Marokkaan",
    "Surinamer",
    "Indonesier",
    "Antiliaan",
    "Caribisch",
    "Oost Europees",
    "Christen",
    "arbeidsmigrant",
    "werkzoeker",
    "flexmigrant",
    "buitenlander",
    "veiligelander",
    # Autochtoon
    "Nederlander",
    "Nederlands",
    "Hollander",
    "Hollands",
    "autochtone Nederlander",
    "echte Nederlander",
    "echte Hollander",
    "allochtone Nederlander",
    "witte Nederlander",
    "blanke Nederlander",
    "blanke Hollander",
    "autochtoon",
    "kolonist",
    # Slang
    "Mocro",
    "Suri",
    "Kaaskop",
    "Indo",
    # Institutioneel
    "werkvergunning",
    "expat",
    "integratie",
    "inburgeren",
    "inburgering",
    "assimilatie",
    "Richtlijn Tijdelijke Bescherming",
]

PLURAL_SUBJECTS = [
    # Actualiteiten
    "Asiel Zoekers Centra",
    # Allochtoon
    "allochtonen",
    "Marokkanen",
    "Antilianen",
    "Oost Europeanen",
    "autochtonen",
]

DESCRIPTIVE_ADJECTIVES = [
    "bedreiging",
    "gevaar",
    "risico",
    "intimiderend"
    "verrijking",
    "aanwinst",
    "versterking"
    "plicht",
    "taak",
    "opdracht",
    "verantwoordelijkheid",
    "last",
    "kwelling",
    "ongerief",
    "ongemak",
    "verplichting",
    "voorschrift",
    "noodzaak",
    "belasting",
    "hinder",
    "kansloos",
    "hopeloos",
    "uitzichtloos",
    "zonder mogelijkheden",
    "kansrijk",
    "veelbelovend",
    "kansarm",
    "perspectiefloos",
    "weinig mogelijkheden",
    "mislukt"
    "geflopt",
    "gefaald",
    "mislukte",
    "mislukkeling",
    "terrorist",
    "geweldpleger",
    "misdadiger",
    "verkrachter",
    "moordenaar",
    "fraudeur",
    "terroristische"
    "onschuldig",
    "ongevaarlijk",
    "lief",
    "geen vlieg kwaad",
    "gevaarlijk",
    "riskant",
    "een kans",
    "mogelijkheid",
    "gelegenheid",
    "toevoeging",
    "aanvulling",
    "crimineel",
    "delinquent",
    "veroordeeld",
    "schuldig",
    "oververtegenwoordigd",
    "bovengemiddeld",
    "huisvesting",
    "onderdak",
    "inwoning",
    "verblijf",
    "onderkomen",
    "wonen",
    "vestigen",
    "vertoeven",
    "huisvesten",
    "verblijven",
    "smokkelen",
    "bedriegen",
    "frauderen",
    "mensenhandel",
    "mensensmokkel",
    "economisch",
    "economische",
    "werk",
    "arbeid",
    "bezigheid",
    "betrekking",
    "functie",
    "inkomen",
    "loon"
    "werk en inkomen",
    "uitkering",
    "bijslag",
    "compensatie",
    "werkloos",
    "zonder werk",
    "ondernemen",
    "opzetten",
    "eigen bedrijf",
    "onderneming",
    "eenmanszaak",
    "zielig",
    "treurig",
    "uitbuiten",
    "uitbuiters",
    "uitkering trekkers",
    "fraudeurs",
    "ondankbaar",
    "bureaucratisch",
    "bureaucratische",
    "onterecht",
    "uitbuiting",
    "uitbuiters",
    "Turkse",
    "Marokkaanse",
    "Surinaamse",
    "Indische",
    "Antiliaanse",
    "zielepoten",
    "bevoorrecht",
    "privilege",
    "terugkeren",
    "blijven",
    "illegaliteit",
    "dakloos",
    "normen en waarden",
    "andere cultuur",
    "gediscrimineerd",
    "racisten",
    "racistisch",
    "superieur",
    "supremacy",
    "ras",
    "sociaal-economisch",
    "achtergrond",
    "afkomst",
    "moedig",
    "heldhaftig",
    "patriottistisch",
    "onderdrukt",
    "lui",
    "corrupt",
    "uitzetten",
    "natuurramp",
    "opwarming van de aarde",
    "overstroming",
    "hongersnood",
    "water tekort",
    "mislukte oogst",
    "voedselprijzen",
    "land van herkomst",
]

immigranten = DiscourseConfiguration(
    title="Immigranten",
    description="Nederland is aantrekkelijk voor mensen om verschillende redenen. "
                "In Nederland zelf is niet iedereen het eens hoe we met deze nieuwe mensen om moeten gaan.",
    language="nl",
    topics=["migrant", "vluchteling", "statushouder", "buitenlander", "veiligelander"],
    singular_subjects=SINGULAR_SUBJECTS,
    plural_subjects=PLURAL_SUBJECTS,
    descriptive_adjectives=DESCRIPTIVE_ADJECTIVES
)
