# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empty_schema_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpresourcemock',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
