SINGULAR_SUBJECTS = [
    "AZC",
    "Asiel Zoekers Centrum"
]

PLURAL_SUBJECTS = [
    "oorlog slachtoffers",
    "Syrische vluchtelingen",
    "Asiel Zoekers Centrum",
    "Asiel Zoekers Centra",
    "AZC",
    "immigranten",
    "Moslims",
    "autochtone Nederlanders",
    "allochtone Nederlanders",
    "echte hollander",
    "hollander",
    "hollands",
    "witte Nederlanders",
    "zwarte Nederlanders"
    "vluchtelingen",
    "statushouders",
    "illegalen",
    "eerste generatie",
    "tweede generatie",
    "derde generatie",
    "1e generatie",
    "2e generatie",
    "3e generatie",
    "autochtoon",
    "allochtoon",
    "smokkelaar",
    "Molukker",
    "Turk",
    "Marokkaan",
    "Surinamer",
    "Indonesier",
    "Koninklijk Nederlands Indisch Leger",
    "Koninklijk Nederlandsch Indisch Leger",
    "KNIL",
    "Antiliaan",
    "kolonisten"
    "werkvergunning",
    "expats",
    "arbeidsmigranten",
    "flexmigranten",
    "buitenlanders",
    "integratie"
]

DESCRIPTIVE_ADJECTIVES = [
    "bedreiging",
    "verrijking",
    "een plicht",
    "een last",
    "verplicht",
    "belasting",
    "kansloos",
    "kansrijk",
    "kansarm",
    "mislukt"
    "mislukte"
    "terrorist",
    "terroristische"
    "onschuldig",
    "gevaarlijk",
    "een kans",
    "toevoeging",
    "crimineel",
    "oververtegenwoordigd",
    "huisvesting"
    "wonen",
    "smokkelen",
    "mensenhandel",
    "economisch",
    "economische",
    "werk",
    "inkomen"
    "werk en inkomen",
    "uitkering",
    "werkloos",
    "ondernemen",
    "eigen bedrijf",
    "zielig",
    "uitbuiten",
    "uitbuiters",
    "uitkering trekkers",
    "fraudeurs",
    "ondankbaar",
    "bureaucratisch",
    "bureaucratische",
    "onterecht",
    "uitbuiting",
    "uitbuiters",
    "Turkse",
    "Marokkaanse",
    "Surinaamse",
    "Indische",
    "Antiliaanse",
    "zielepoten",
    "bevoorrecht",
    "privilege",
    "terugkeren",
    "blijven",
    "illegaliteit",
    "dakloos",
    "normen en waarden",
    "andere cultuur",
    "gediscrimineerd",
    "racisten",
    "racistisch",
    "superieur",
    "supremacy",
    "ras",
    "sociaal-economisch",
    "achtergrond",
    "afkomst"
]
