from core.utils.tests.configuration import TestConfigurationType, TestConfigurationProperty, TestLoadConfigDecorator

from core.processors.tests.resources import TestHttpResourceProcessorGet, TestHttpResourceProcessorPost
from core.processors.tests.extraction import TestExtractProcessorHTML