# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0026_auto_20180818_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFeatures',
        ),
    ]
