# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-21 12:53
from __future__ import unicode_literals

import core.processors.mixins
import datagrowth.configuration.fields
from django.db import migrations, models
import django.db.models.deletion
import json_field.fields


class Migration(migrations.Migration):

    replaces = [('visual_translations', '0001_initial'), ('visual_translations', '0002_auto_20160219_1442'), ('visual_translations', '0003_auto_20160225_2307'), ('visual_translations', '0004_auto_20160328_1112'), ('visual_translations', '0005_visualtranslationsbriccommunity'), ('visual_translations', '0006_auto_20160417_2047'), ('visual_translations', '0007_webimagedownload'), ('visual_translations', '0008_auto_20190402_0928'), ('visual_translations', '0009_alter_data_hash'), ('visual_translations', '0010_on_delete')]

    initial = True

    dependencies = [
        ('core', '0004_communitymock'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_auto_20160226_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualTranslationsCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=255)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('kernel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('Aborted', 'Aborted'), ('Asynchronous', 'Asynchronous'), ('New', 'New'), ('Ready', 'Ready'), ('Synchronous', 'Synchronous')], default='New', max_length=255)),
                ('current_growth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Growth')),
                ('kernel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Visual translation',
                'verbose_name_plural': 'Visual translations',
            },
            bases=(models.Model, core.processors.mixins.ProcessorMixin),
        ),
        migrations.RunSQL(
            sql="UPDATE django_content_type\n         SET model = 'visualtranslationseucommunity'\n         WHERE model = 'visualtranslationscommunity' AND\n               app_label = 'visual_translations';",
            reverse_sql="UPDATE django_content_type\n                 SET model = 'visualtranslationscommunity'\n                 WHERE model = 'visualtranslationseucommunity' AND\n                       app_label = 'visual_translations';",
        ),
        migrations.RenameModel(
            old_name='VisualTranslationsCommunity',
            new_name='VisualTranslationsEUCommunity',
        ),
        migrations.CreateModel(
            name='VisualTranslationsBRICCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(db_index=True, max_length=255)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('kernel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('Aborted', 'Aborted'), ('Asynchronous', 'Asynchronous'), ('New', 'New'), ('Ready', 'Ready'), ('Retry', 'Retry'), ('Synchronous', 'Synchronous')], default='New', max_length=255)),
                ('current_growth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Growth')),
                ('kernel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Visual translations (BRIC)',
                'verbose_name': 'Visual translation (BRIC)',
            },
            bases=(models.Model, core.processors.mixins.ProcessorMixin),
        ),
        migrations.AlterModelOptions(
            name='visualtranslationseucommunity',
            options={'verbose_name': 'Visual translation (EU)', 'verbose_name_plural': 'Visual translations (EU)'},
        ),
        migrations.CreateModel(
            name='WebImageDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', json_field.fields.JSONField(default=None, help_text='Enter a valid JSON object')),
                ('head', json_field.fields.JSONField(default='{}', help_text='Enter a valid JSON object')),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='visualtranslationseucommunity',
            name='views',
        ),
        migrations.AlterField(
            model_name='visualtranslationseucommunity',
            name='state',
            field=models.CharField(choices=[('Aborted', 'Aborted'), ('Asynchronous', 'Asynchronous'), ('New', 'New'), ('Ready', 'Ready'), ('Retry', 'Retry'), ('Synchronous', 'Synchronous')], default='New', max_length=255),
        ),
        migrations.AlterField(
            model_name='visualtranslationseucommunity',
            name='current_growth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Growth'),
        ),
        migrations.AlterField(
            model_name='visualtranslationseucommunity',
            name='kernel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
    ]
