# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 23:02
from __future__ import unicode_literals

from django.db import migrations
import json_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online_discourse', '0001_squashed_0010_collection_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='schema',
            field=json_field.fields.JSONField(blank=True, default=dict, help_text='Enter a valid JSON object'),
        ),
        migrations.AlterField(
            model_name='document',
            name='schema',
            field=json_field.fields.JSONField(blank=True, default=dict, help_text='Enter a valid JSON object'),
        ),
    ]
