# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_discourse', '0003_elastic_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complexityanalysis',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='webcontentdownload',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='webtextresource',
            name='data_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
