# Generated by Django 3.2 on 2021-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_discourse', '0005_on_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='document',
            name='schema',
        ),
        migrations.AlterField(
            model_name='complexityanalysis',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='complexityanalysis',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='elasticindex',
            name='configuration',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='webcontentdownload',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webcontentdownload',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webtextresource',
            name='head',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='webtextresource',
            name='request',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='webtexttikaresource',
            name='command',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
