# Generated by Django 3.2.19 on 2023-08-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_discourse', '0006_datagrowth_v017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComplexityAnalysis',
        ),
    ]
