PRODUCT_TRANSLATIONS = {
    "verse knoflook - waanzinnig aroma": "knoflook, verse",
    "alouette aardappel van boerderij gaos": "aardappel, alouette",
    "10-zadenbol brood desem, van eigen graan (gesneden)": "brood, 10-zadenbol desem",
    "10-zadenbol  brood desem, van eigen graan (gesneden)": "brood, 10-zadenbol desem",
    "brood zonnelied 10 zaden bol, desem gesneden": "brood, 10-zadenbol desem",
    "afbak baguettes": "baguettes, afbak",
    "ambachtelijke ontbijtkoek": "ontbijtkoek, ambachtelijke",
    "bos verse platte peterselie": "peterselie, bos verse platte",
    "afbak breekbrood van eigen graan": "brood, afbak breekbrood",
    "pers sinaasappels navelina": "sinaasappels, pers, navelina",
    "trostomaat": "tomaat, tros",
    "zeeuwse zeewierburger - prolaterre": "zeewierburger, zeeuwse, prolaterre",
    "zonnelied vruchtenbol - gist": "brood, vruchtenbol, gist",
    "chioggia bieten": "bieten, chioggia",
    "crèmehoning - klaver en zo": "honing, crème",
    "gele uien": "uien, gele",
    "geraspte parmigiano reggiano": "parmigiano reggiano, geraspte",
    "gerookte spekblokjes": "spekblokjes, gerookte",
    "gewassen peen": "peen, gewassen",
    "groene pompoen": "pompoen, groene",
    "halfvolle melk van zuivelboerderij fam. de lange uit de weerribben": "melk, halfvolle",
    "koe mozzarella - castelli": "mozzarella, koe - castelli",
    "magere stooflappen": "stooflappen, magere",
    "oranje pompoen": "pompoen, oranje",
    "rode bieten": "bieten, rode",
    "rode eikenbladsla": "eikenbladsla, rode",
    "rode kool met appel verpakt": "kool, rode met appel verpakt",
    "rodelika winterpeen": "peen, winter (rodelika)",
    "runder rookworst": "rookworst, runder",
    "spelt speculaasjes": "speculaasjes, spelt",
    "topaz - appel voor fijnproevers": "appelen, topaz",
    "vers gerookte makreelfilet - meij": "makreelfilet, gerookt",
    "verse gember": "gember",
    "verse rode peper": "peper, rood",
    "volle melk - weerribben": "melk, volle",
    "volle yoghurt van klaas de lange uit nationaal park de weerribben": "yoghurt, volle",
    "witte kool van reggy": "kool, witte",
    "zonnelied brood volkoren - gist - gesneden": "brood, volkoren - gist - gesneden",
    "zonnelied noten rozijnenslof - desem": "brood, noten rozijnenslof - desem",
    "biolissimo cherry trostomaatjes": "tomaatjes, cherry tros",
    "elstar appels": "appels, elstar",
    "fries roggebrood": "roggebrood, fries",
    "groene of rode eikenbladsla van reggy - prachtige kroppen!": "sla, eikenblad, groene of rode",
    "halfvolle yoghurt weeribben": "yoghurt, halfvolle",
    "kleintje zonnelied brood - kasteeltje - gist": "brood, kasteeltje - gist",
    "little gem sla": "sla, little gem",
    "moro bloedsinaasappels": "bloedsinaasappels, moro",
    "paarse koolrabi": "koolrabi, paarse",
    "pitloze mix olijven": "olijven, pitloze mix",
    "punt paprika's": "paprika's, punt",
    "rode paprika": "paprika, rode",
    "zonnezaad brood volkoren - desem - gesneden": "brood, zaden - volkoren - desem - gesneden",
    "bloedsinaasappels, moro": "sinaasappels, bloed, moro",
    "groene koolrabi van reggy": "koolrabi, groene",
    "polderhoen kipfilet": "kipfilet, polderhoen",
    "verse tijm": "tijm, verse",
    "weekendbroodje: dadel-walnotenbol": "brood, dadel-walnotenbol",
    "zonnelied brood volkoren - desem - gesneden": "brood, volkoren - desem - gesneden",
    "aardappel frieslanders - 1 kg - nieuwe oogst van familie geraets": "aardappel, frielanders",
    "gedroogde knoflook": "knoflook, gedroogde",
    "goede nacht thee uit de kruidentuin": "thee, goede nacht",
    "groene asperges": "asperges, groene",
    "witte asperges - 2. klas": "asperges, witte, 2e klas",
    "witte asperges 1. klas": "asperges, witte, 1e klas",
    "zomer aardbeien": "aardbeien",
    "volle yomio - zuiver zuivel": "yomio, volle",
    "slagroom van zuivelboerderij fam. de lange uit de weerribben": "slagroom",
    "regenboog peen": "peen, regenboog",
    "handsinaasappels rechtstreeks uit de boomgaard van dani en isa uit spanje": "sinaasappels, hand",
    "kromme komkommers": "komkommer, kromme",
    "kropsla van de eerste": "sla, krop",
    "portobello paddenstoel": "paddenstoelen, portobello",
    "eryngii koningsoesterzwam": "paddenstoelen, eryngii koningsoesterzwam",
    "verse doperwten": "doperwten, verse",
    "verse kapucijners": "kapucijners, verse",
    "verse peultjes": "peultjes, verse",
    "butternut pompoen": "pompoen, butternut",
    "2e klasse rode paprika": "paprika, rode, 2e klas",
    "cocktail trostomaatjes": "tomaatjes, tros, cocktail",
    "gele paprika klasse 2": "paprika, gele, 2e klas",
    "rode druivensap - 100% sap": "sap, rode druiven",
    "verse kurkuma": "kurkuma, verse",
    "frans knipje brood van eigen graan": "brood, frans knipje",
    "gele courgette": "courgette, geel",
    "kastanjechampignons": "champignons, kastanje",
    "losse tomaten": "tomaten, losse",
    "rode bessen van richard sjerps": "bessen, rode",
    "verse koriander": "koriander, verse",
    "volle kwark van zuivelboerderij fam. de lange uit de weerribben": "kwark, volle",
    "warm gerookte zalmmoot": "zalmmoot, warm gerookte",
    "blauwe bessen": "bessen, blauwe",
    "batavia sla": "sla, batavia",
    "cocktail tomaat": "tomaten, cocktail",
    "cripps pink appels - nieuwe buitenlandse oogst!": "appels, pink",
    "gekleurde snijbiet van reggy": "bieten, snij",
    "gekookte bietjes": "bieten, gekookte",
    "gesneden roggebrood van boerderij-bakker zonnelied": "brood, rogge, gesneden",
    "palestijnse olijfoliesoep met linzen": "soep, olijfolie met linzen",
    "snelkookrijst half volkoren": "rijst, snelkook, half volkoren",
    "verse suikermais": "suikermais, verse",
    "verse uien met steel, maar zonder loof": "uien, vers zonder loof",
    "witte druiven": "druiven, witte",
    "bospeen": "peen, bos",
    "bosui": "ui, bos",
    "chinese kool": "kool, chinese",
    "eieren van eko boerderij de eerste, 10 st": "eieren, 10 st",
    "eieren van eko boerderij de eerste, 6 st": "eieren, 6 st",
    "graffiti aubergine": "aubergine, graffiti",
    "grasboter": "boter, gras",
    "rode kool": "kool, rode",
    "verse bladselderij": "bladselderij, verse",
    "zoete bataat": "bataat, zoete",
    "bosbieten nieuwe oogst!": "bieten, bos"
}


def get_product(title):
    # Clean input
    product = title.lower().strip()
    # Strip any prefix variants of "biologisch"
    if product.startswith("bio"):
        product = " ".join(product.split(" ")[1:]).strip()
    # Lookup product in translation table to see if their are better strings
    return PRODUCT_TRANSLATIONS.get(product, product)
