# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_research', '0005_auto_20180813_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webtextresource',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='WebTextResource',
        ),
    ]
