django:
  debug: 1
  database_name: datascope
  database_user: django
  secret_key: "secret-key"
  database_password: "secret"
  administrator:
    name: "Anonymous"
    email: "email"
  manager:
    name: "Anonymous"
    email: "email"
datascope:
  google_cx: "004613812033868156538:5pcwbuudj1m"
  data_dir: ./data
  google_api_key: "secret"
  locafora_password: "secret"
  wiki_user: "Wiki Feed Bot"
  wiki_password: "secret"
  email_user: "anonymous"
  email_password: "secret"
postgres:
  credentials:
  host: "127.0.0.1"
  port: 5432
elastic_search:
  host: "http://elasticsearch:9200"
  password: None
redis:
  broker_url: "redis://redis:6379/0"
